/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./BenefitCard.css";

function BenefitCard({ icon, title, description }) {
  return (
    <div className={styles.benefitCard}>
      <img src={icon} alt={`${title} icon`} className={styles.benefitIcon} />
      <h3 className={styles.benefitTitle}>{title}</h3>
      <p className={styles.benefitDescription}>{description}</p>
    </div>
  );
}

export default BenefitCard;
