/**
 * This code was generated by Builder.io.
 */
import React from "react";
import BenefitCard from "./BenefitCard";
import styles from "./Benefits.css";

const benefitsData = [
  {
    icon: "img",
    title: "Exposure",
    description:
      "Our advanced spyware detection engine can identify if a device contains spyware or bugging software.",
  },
  {
    icon: "img",
    title: "R&D and Innovation",
    description:
      "Find malicious keyboards installed on your device that could allow someone to record things you type (e.g. passwords).",
  },
  {
    icon: "img",
    title: "Networking",
    description:
      "Check which apps can access your location, microphone or camera. Get alerted if a known tracking app is installed.",
  },
  {
    icon: "img",
    title: "Enhancing Projects and education",
    description:
      "Analyze your operating system for signs of tampering that could compromise security, such as Jailbreaking.",
  },
  {
    icon: "img",
    title: "Opportunities",
    description:
      "Our intelligent scan will either safely remove threats for you or provide easy-to-follow instructions.",
  },
  {
    icon: "img",
    title: "Practical Applications",
    description:
      "We create easy to use apps that can check your device for vulnerabilities in a matter of minutes.",
  },
];

function Benefits() {
  return (
    <section className={styles.benefitsSection}>
      <h2 className={styles.benefitsTitle}>Benefits of Contribution</h2>
      <div className={styles.benefitsGrid}>
        {benefitsData.map((benefit, index) => (
          <BenefitCard key={index} {...benefit} />
        ))}
      </div>
    </section>
  );
}

export default Benefits;
