/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./Footer.css";

function Footer() {
  return (
    <footer className={styles.footer}>
      <div className={styles.footerContent}>
        <div className={styles.logoSection}>
          <img src="img" alt="SAE Logo" className={styles.footerLogo} />
          <img
            src="img"
            alt="SAE Text Logo"
            className={styles.footerTextLogo}
          />
        </div>
        <div className={styles.infoSection}>
          <h3 className={styles.infoTitle}>Collegiate Club</h3>
          <h2 className={styles.saeTitle}>SAE</h2>
          <address className={styles.address}>
            TACK {/* Ka full form */} {/* Or pura tack ka address */}
            <br />
            IIT (BHU) Varanasi. India
            <br />
            PIN: 221005
          </address>
        </div>
        <div className={styles.socialsSection}>
          <h3 className={styles.socialsTitle}>Socials</h3>
          <ul className={styles.socialsList}>
            <li>
              <a href="#instagram" className={styles.socialLink}>
                <img src="img" alt="Instagram" /> Instagram
              </a>
            </li>
            <li>
              <a href="#facebook" className={styles.socialLink}>
                <img src="img" alt="Facebook" /> Facebook
              </a>
            </li>
            <li>
              <a href="#linkedin" className={styles.socialLink}>
                <img src="img" alt="LinkedIn" /> LinkedIn
              </a>
            </li>
            <li>
              <a href="#email" className={styles.socialLink}>
                <img src="img" alt="Email" /> E-mail
              </a>
            </li>
          </ul>
        </div>
        <div className={styles.newsletterSection}>
          <h3 className={styles.newsletterTitle}>Stay up to date</h3>
          <form className={styles.newsletterForm}>
            <label htmlFor="emailInput" className={styles.visuallyHidden}>
              Your email address
            </label>
            <div className={styles.inputWrapper}>
              <input
                type="email"
                id="emailInput"
                placeholder="Your email address"
                className={styles.emailInput}
              />
              <button type="submit" className={styles.submitButton}>
                <img src="img" alt="Submit" className={styles.submitIcon} />
              </button>
            </div>
          </form>
          <img src="img" alt="" className={styles.footerDecoration} />
        </div>
      </div>
    </footer>
  );
}

export default Footer;
