/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./Header.css";

function Header() {
  return (
    <header className={styles.header}>
      <img src="img" alt="Trident Logo" className={styles.logo} />
      <nav className={styles.navigation}>
        <ul className={styles.navList}>
          <li className={styles.navItem}>
            <a href="#home" className={`${styles.navLink} ${styles.active}`}>
              Home
            </a>
          </li>
          <li className={styles.navItem}>
            <a href="#about" className={styles.navLink}>
              About
            </a>
          </li>
          <li className={styles.navItem}>
            <a href="#events" className={styles.navLink}>
              Events
            </a>
          </li>
          <li className={styles.navItem}>
            <a href="#blogs" className={styles.navLink}>
              Blogs
            </a>
          </li>
          <li className={styles.navItem}>
            <a href="#projects" className={styles.navLink}>
              Projects
            </a>
          </li>
        </ul>
      </nav>
      <button className={styles.tridentButton}>Trident</button>
    </header>
  );
}

export default Header;
