/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./Sponsors.css";

function Sponsors() {
  return (
    <section className={styles.sponsorsSection}>
      <h2 className={styles.sponsorsTitle}>Our Sponsors</h2>
      <div className={styles.sponsorsGrid}>
        <img src="img" alt="Sponsor 1" className={styles.sponsorLogo} />
        <img src="img" alt="Sponsor 2" className={styles.sponsorLogo} />
        <img src="img" alt="Sponsor 3" className={styles.sponsorLogo} />
      </div>
    </section>
  );
}

export default Sponsors;
