/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./Team.css";

function Team() {
  const teamCategories = [
    "Helm",
    "Aerodynamics",
    "Vehicle Dynamics",
    "Structures",
    "Marketing",
    "Web Team",
  ];

  return (
    <section className={styles.teamSection}>
      <h2 className={styles.teamTitle}>Meet Our Team</h2>
      <div className={styles.teamContent}>
        <div className={styles.teamCategories}>
          {teamCategories.map((category, index) => (
            <button key={index} className={styles.categoryButton}>
              {category}
              {category === "Helm" && (
                <img src="img" alt="Helm icon" className={styles.helmIcon} />
              )}
            </button>
          ))}
        </div>
        <div className={styles.teamPhotos}>
          <img src="img" alt="Team photo 1" className={styles.teamPhoto} />
          <img src="img" alt="Team photo 2" className={styles.teamPhoto} />
        </div>
      </div>
    </section>
  );
}

export default Team;
