/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Header from "./Header";
import Benefits from "./Benefits";
import Sponsors from "./Sponsors";
import Team from "./Team";
import Footer from "./Footer";
import styles from "./TridentTeam.css";

function TridentTeam() {
  return (
    <div className={styles.tridentPage}>
      <Header />
      <main className={styles.mainContent}>
        <section className={styles.teamIntro}>
          <h1 className={styles.teamTitle}>Team Trident</h1>
          <p className={styles.teamDescription}>
            SAE (Society of Automotive Engineers) aims to give a platform to
            people who wish to learn about and build automobiles. Our teams take
            part in various RC and automotive events all round the year....
          </p>
        </section>
        <Benefits />
        <Sponsors />
        <Team />
      </main>
      <Footer />
    </div>
  );
}

export default TridentTeam;
